env:
  browser: true
  commonjs: true
  es6: true
extends: 'prettier'
parserOptions:
  sourceType: module
plugins: ['prettier']
rules:
  prettier/prettier: ['error', {
      useTabs: true,
      singleQuote: true
    }]
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
