env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
plugins: ['prettier']
rules:
  prettier/prettier: 'error'
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
